#define FPGA_H0_BASE_ADDR 0x400 //byte allign
#define FPGA_H0_SIZE 14
#define FPGA_CODE0_BASE_ADDR 0x000//byte allign
#define FPGA_CODE0_SIZE 70
#define FPGA_SCRACHPAD_MEM_BASE_ADDR 0x0
#define FPGA_SINGLE_MEM_SIZE 2097152
#define FPGA_CONTROL_REG_ADDR_OFFSET 0x800//byte allign
#define FPGA_CORE_CNTL_START_MASK 0x1
#define FPGA_CORE_STASUS_FINISHED_MASK 0x1
#define FPGA_STATUS_REG_ADDR_OFFSET 0x800//byte allign
#define FPGA_STATUS_FLAG_CLEAR_ADDR_OFFSET 0x804//byte allign
#define FPGA_RESET_REG_ADDR_OFFSET 0x808//byte allign

#define FPGA_CONTROL_REG_SPACE_SIZE 0x1000//byte allign
#define FPGA_SRATCH_MEM_SPACE_SIZE 0x200000//byte allign
